apiVersion: apps/v1
kind: Deployment
metadata:
  name: bw01_apigateway-deployment
  labels:
    app: bw01_apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bw01_apigateway
  template:
    metadata:
      labels:
        app: bw01_apigateway
    spec:
      containers:
        - name: bw01_apigateway
          image: rishad004/bw01_apigateway:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bw01_apigateway-service
spec:
  selector:
    app: bw01_apigateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer